### ISSUE TITLE
docker image requires token file

### ISSUE THREAD

**Issue by agsmith** [tomwilkie/kube-api-exporter#5]
Hi-

I'm encountering an issue when running this docker image.  
`core@cmce-k8s-worker-4 ~ $ sudo docker run tomwilkie/kube-api-exporter
Traceback (most recent call last):
  File "/main.py", line 90, in <module>
    api = pykube.HTTPClient(pykube.KubeConfig.from_service_account())
  File "/usr/lib/python3.5/site-packages/pykube/config.py", line 22, in from_service_account
    with open(os.path.join(path, "token")) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'`

Do I need to provide this token file in a volume mount?

**Comment by tomwilkie** [comment]
Hi there!  This image is designed to be run under Kubernetes, where it will automatically get credentials (such as a token file in that location).   See http://kubernetes.io/docs/user-guide/service-accounts/

**Comment by agsmith** [comment]
I am running under kubernetes, the above docker run command was trying to run the container manually.  When I try to deploy the pod, it enters a CrashBackOffLoop state and the log shows me:

`root@6515dc9b090a:kube-api-exporter# kubectl --context=cmce --namespace=monitoring log kube-api-exporter-403490417-285y5
Traceback (most recent call last):
  File "/main.py", line 90, in <module>
    api = pykube.HTTPClient(pykube.KubeConfig.from_service_account())
  File "/usr/lib/python3.5/site-packages/pykube/http.py", line 32, in __init__
    self.url = self.config.cluster["server"]
  File "/usr/lib/python3.5/site-packages/pykube/config.py", line 175, in cluster
    return self.clusters[self.contexts[self.current_context]["cluster"]]
  File "/usr/lib/python3.5/site-packages/pykube/config.py", line 136, in clusters
    BytesOrFile.maybe_set(c, "certificate-authority")
  File "/usr/lib/python3.5/site-packages/pykube/config.py", line 200, in maybe_set
    d[file_key] = cls(d[file_key])
  File "/usr/lib/python3.5/site-packages/pykube/config.py", line 214, in __init__
    self._bytes = base64.b64decode(data)
  File "/usr/lib/python3.5/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding`

I am running my apiserver with the following options:

``` /opt/bin/kube-apiserver
  --service-account-key-file=/opt/bin/kube-serviceaccount.key 
  --apiserver-count=3 
  --service-account-lookup=false 
  --secure-port=6443 
  --admission-control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota 
  --runtime-config=extensions/v1beta1/deployments=true,api/v1=true 
  --allow-privileged=true
  --insecure-bind-address=0.0.0.0 
  --insecure-port=8080 
  --kubelet-https=true 
  --service-cluster-ip-range=192.168.0.0/16 
  --etcd-servers=http://127.0.0.1:2379 
  --public-address-override=96.119.244.103 
  --logtostderr=true
```

Any idea what I am missing?

**Comment by tomwilkie** [comment]
It seems to be failing to parse your service account credentials. I'd would
start a pod and take a look at the credentials to see if they are well
formed. What version on kubernetes are you using?

**Comment by agsmith** [comment]
I am running k8s 1.3.8.  How can I look at the creds ?

**Comment by tomwilkie** [comment]
I'm just on my way to the airport but when I get there I'll send you the
commands.

If this open shift or tectonic? Or plain old OSS kubernetes?

**Comment by agsmith** [comment]
Just regular kubernetes 1.3.8.  Thanks

**Comment by tomwilkie** [comment]
Try:

```
$ kubectl run -t -i --image=alpine test -- /bin/sha
Waiting for pod default/test-448237823-i6ftf to be running, status is Pending, pod ready: false

Hit enter for command prompt

/ # cat /var/run/secrets/kubernetes.io/serviceaccount/token 
```

Don't paste the result, just make sure it looks like a base64 encoded value.  You can also poke around at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`, and check it looks like a certificate.

**Comment by agsmith** [comment]
Thanks Tom.  That just goes into a CrashBackOffLoop too
`ot@4b2cc5028e92:/opt/kubernetes-deployments/environments# kubectl --context=cmce --namespace=monitoring get pods`
`NAME                                READY     STATUS             RESTARTS   AGE`
`kube-api-exporter-403490417-285y5   0/1       CrashLoopBackOff   21         1h`
`node-exporter-1c82z                 1/1       Running            0          8h`
`node-exporter-4kwpe                 1/1       Running            0          8h`
`node-exporter-hemni                 1/1       Running            0          8h`
`node-exporter-s3j48                 1/1       Running            0          8h`
`node-exporter-sdslh                 1/1       Running            0          8h`
`prometheus-193001143-oqpy7          1/1       Running            0          8h`
`test-3193344352-6ktex               0/1       CrashLoopBackOff   3          1m`
`root@4b2cc5028e92:/opt/kubernetes-deployments/environments# kubectl --context=cmce --namespace=monitoring log test-3193344352-6ktex`
`Error from server: Unrecognized input header`

**Comment by tomwilkie** [comment]
Looks like you might be hitting https://github.com/kubernetes/kubernetes/issues/16670

It suggests the container is exiting quickly.  Do you have a copy of what you typed?

**Comment by agsmith** [comment]
This is what I typed:
`kubectl --context=cmce --namespace=monitoring run -t -i --image=alpine test -- /bin/sha`

**Comment by tomwilkie** [comment]
`/bin/sha` should be `/bin/sh`

**Comment by tomwilkie** [comment]
My bad, sorry!

**Comment by agsmith** [comment]
Ha!  I thought that was strange, but I figured it would dump out a SHA hash or something :)

Thanks

```
root@6515dc9b090a:/opt/kubernetes-deployments/environments/monitoring/ndc_cmc_e/kube-api-exporter# kubectl --context=cmce --namespace=monitoring run -t -i --image=alpine test2 -- /bin/sh
Waiting for pod monitoring/test2-2449707363-3sa2c to be running, status is Pending, pod ready: false

Hit enter for command prompt

/ # ls
bin      etc      lib      media    proc     run      srv      tmp      var
dev      home     linuxrc  mnt      root     sbin     sys      usr
/ # cat /var/run/secrets/kubernetes.io/serviceaccount/token
```

The output of the token is valid Base64 and decodes into:

```
{"alg":"RS256","typ":"JWT"}{"iss":"kubernetes/serviceaccount","kubernetes.io/serviceaccount/namespace":"monitoring","kubernetes.io/serviceaccount/secret.name":"default-token-yi904","kubernetes.io/serviceaccount/service-account.name":"default","kubernetes.io/serviceaccount/service-account.uid":"<redacted>","sub":"system:serviceaccount:monitoring:default"<redacted>}
```

**Comment by agsmith** [comment]
/ # /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
/bin/sh: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: not found

**Comment by tomwilkie** [comment]
This seems related: https://github.com/kubernetes/heapster/issues/429#issuecomment-125170119

It looks like you need to add some more arguments to your api-server.

**Comment by agsmith** [comment]
That looks promising.  Thanks for all of your help Tom!  Safe travels!

**Comment by tomwilkie** [comment]
No worries - let me know how you get on!

**Comment by tomwilkie** [comment]
@agsmith did you find out what the problem was in the end?
