### ISSUE TITLE
Invalid memory errors

### ISSUE THREAD

**Issue by wirtsi** [tomwilkie/kube-api-exporter#6]
Hi ...

I use your tool to monitor our kubernetes deployment status. We use some pods that are rather short lived (ie. they are spun up, do one thing in between 30s to 5m and are then shut down)

With these pods, I get the following errors in the logs

"time="2016-10-14T10:43:18Z" level=warning msg="Error expanding alert template NotReadyPods with data '{map[job:kubernetes-endpoints containerStatuses:1 name:expire-orders-609-tm3ff namespace:default **name**:k8s_pod_status_ready instance:10.184.1.23:80 kubernetes_namespace:default kubernetes_name:kube-api-exporter-v1] 0}': runtime error: invalid memory address or nil pointer dereference" source="alerting.go:196"

This causes my alerts to fire because apparently it leaves kube-api-exporter pod in a flaky state. I am using this Query to check bad pods

ALERT NotReadyPods
  IF (k8s_pod_status_ready == 0)
  FOR 5m
  LABELS {severity="critical"}
  ANNOTATIONS {description="Pod {{$labels.namespace}}/{{$label.name}} is becoming ready for more than 5 mins.", summary="Pod {{$labels.namespace}}/{{$label.name}} is in not ready."}

This is the alarm that fires then I get above error message in my logs

Bests

**Comment by tomwilkie** [comment]
Hi there.  What components gives that alert?  Prometheus?

**Comment by tomwilkie** [comment]
Yes must be.  Comes from here: https://github.com/prometheus/prometheus/blob/master/rules/alerting.go#L199

**Comment by tomwilkie** [comment]
What Prometheus version are you using?

**Comment by tomwilkie** [comment]
Oh I see the problem: it should be $label**s**.name.

**Comment by wirtsi** [comment]
Nice ... thanks for looking into this 👍
